<?php

/**
 * @file
 * Module file for "Copyright block".
 */

/**
 * Implements hook_block_info().
 *
 * Provides one block named 'Copyright' that is globally cached.
 */
function copyright_block_block_info() {
  $blocks['copyright'] = array(
    'info' => t('Copyright'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 *
 * Renders a HTML-span containing the copyright information.
 */
function copyright_block_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'copyright':

      // Check if an inception year is given.
      $year = variable_get('copyright_block_inceptionyear');
      $currentYear = date('Y', REQUEST_TIME);
      if ($year) {
        // Show something like 2003 - 2011, if not current year.
        if ($year != $currentYear) {
          $year .= ' - ' . $currentYear;
        }
      }
      else {
        // Show only the current year.
        $year = $currentYear;
      }

      // Check if there is a name for the copyright holder.
      $holder = variable_get('copyright_block_copyrightholder');
      if (!$holder) {
        // No holder given, default to site name.
        $holder = variable_get('site_name', '');
      }

      // Create the block.
      $block['subject'] = t('Copyright');
      $block['content'] = '<span class="copyright">&copy; ' . check_plain($holder) . ' ' . $year . '</span>';
      break;
  }
  return $block;
}

/**
 * Implements hook_block_configure().
 *
 * Creates the form data to set the copyright holder and the inception year.
 */
function copyright_block_block_configure($delta = '') {
  $form = array();
  if ($delta == 'copyright') {

    // Plain text field for the name of the copyright holder.
    $form['copyright_block_copyrightholder'] = array(
      '#type' => 'textfield',
      '#title' => t('Copyright holder'),
      '#size' => 64,
      '#description' => t('Name of the copyright holder. Leave empty to use the site name.'),
      '#default_value' => variable_get('copyright_block_copyrightholder'),
    );

    // Plain text field for the year the copyright starts.
    $inceptionyear = variable_get('copyright_block_inceptionyear');
    $form['copyright_block_inceptionyear'] = array(
      '#type' => 'textfield',
      '#title' => t('Copyright starting year'),
      '#size' => 8,
      '#description' => t('Year the copyright starts. Leave empty to only show current year.'),
      '#default_value' => $inceptionyear ? $inceptionyear : '',
    );
  }
  return $form;
}

/**
 * Implements hook_block_save().
 *
 * Stores the copyright holder and the inception year.
 */
function copyright_block_block_save($delta = '', $edit = array()) {
  if ($delta == 'copyright') {
    $copyright_block_copyrightholder = $edit['copyright_block_copyrightholder'];
    if ($copyright_block_copyrightholder == variable_get('site_name', '')) {
      $copyright_block_copyrightholder = '';
    }
    variable_set('copyright_block_copyrightholder', $copyright_block_copyrightholder);
    $copyright_block_inceptionyear = intval($edit['copyright_block_inceptionyear']);
    $current_year = date('Y', REQUEST_TIME);
    if ($copyright_block_inceptionyear > $current_year) {
      $copyright_block_inceptionyear = $current_year;
    }
    variable_set('copyright_block_inceptionyear', $copyright_block_inceptionyear);
  }
}

